//! Faithful port of nextpnr's `DeterministicRNG`.
//!
//! Source: upstream YosysHQ nextpnr `main` @ `4d235150`,
//! `common/kernel/deterministic_rng.h`.
//!
//! ```text
//!  nextpnr -- Next Generation Place and Route
//!
//!  Copyright (C) 2018  Claire Xenia Wolf <claire@yosyshq.com>
//!  Copyright (C) 2018  Serge Bazanski <q3k@q3k.org>
//!
//!  Permission to use, copy, modify, and/or distribute this software for any
//!  purpose with or without fee is hereby granted, provided that the above
//!  copyright notice and this permission notice appear in all copies.
//!
//!  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
//!  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
//!  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
//!  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
//!  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
//!  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
//!  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//! ```
//!
//! The generator is xorshift64*star* (<https://arxiv.org/abs/1402.6246>): the
//! return value is the *pre-advance* state multiplied by a constant, and the
//! state advances with shifts 12/25/27. Every placer and router in nextpnr
//! draws from this stream, so any deviation makes seeds incomparable between
//! the two implementations. Verified against a golden trace generated by the
//! real C++ header -- see `tests/rng_golden_tests.rs`.

/// nextpnr's default RNG state, and the value `rngseed` falls back to for a
/// zero seed.
const DEFAULT_STATE: u64 = 0x3141_5926_5358_9793;

/// The xorshift64star output multiplier.
const MULTIPLIER: u64 = 0x2545_F491_4F6C_DD1D;

/// A faithful port of nextpnr's `DeterministicRNG`.
pub struct DeterministicRng {
    /// `rngstate` in nextpnr.
    state: u64,
}

impl Default for DeterministicRng {
    /// Matches nextpnr's default constructor, `rngstate(0x3141592653589793)`.
    ///
    /// Note this is *not* the same as `new(0)`: nextpnr reaches the default
    /// state from a zero seed only via `rngseed`, which additionally burns
    /// five draws.
    fn default() -> Self {
        Self {
            state: DEFAULT_STATE,
        }
    }
}

impl DeterministicRng {
    /// Create an RNG seeded with `seed`, equivalent to default-constructing
    /// and calling `rngseed(seed)`.
    pub fn new(seed: u64) -> Self {
        let mut rng = Self::default();
        rng.rngseed(seed);
        rng
    }

    /// `rngseed` -- a zero seed falls back to the default state, then five
    /// draws are discarded to wash out low-entropy seeds.
    pub fn rngseed(&mut self, seed: u64) {
        self.state = if seed != 0 { seed } else { DEFAULT_STATE };
        for _ in 0..5 {
            self.rng64();
        }
    }

    /// `rng64` -- xorshift64star.
    ///
    /// The multiply is applied to the state *before* it advances, so the
    /// returned value and the next state come from different points in the
    /// sequence. Getting this order backwards still produces a plausible
    /// stream, which is exactly why it is worth a golden test.
    pub fn rng64(&mut self) -> u64 {
        let retval = self.state.wrapping_mul(MULTIPLIER);

        self.state ^= self.state >> 12;
        self.state ^= self.state << 25;
        self.state ^= self.state >> 27;

        retval
    }

    /// `rng` -- the low 30 bits of a draw.
    pub fn rng(&mut self) -> i32 {
        (self.rng64() & 0x3fff_ffff) as i32
    }

    /// `rng(n)` -- uniform in `[0, n)` by rejection sampling against the next
    /// power of two, which avoids the modulo bias a naive `% n` would carry.
    ///
    /// # Panics
    ///
    /// Panics if `n <= 0`, matching nextpnr's `assert(n > 0)`.
    pub fn rng_n(&mut self, n: i32) -> i32 {
        assert!(n > 0, "rng_n requires n > 0, got {n}");

        // Round n up to a power of two.
        let mut m = n - 1;
        m |= m >> 1;
        m |= m >> 2;
        m |= m >> 4;
        m |= m >> 8;
        m |= m >> 16;
        m += 1;

        loop {
            let x = (self.rng64() & ((m - 1) as u64)) as i32;
            if x < n {
                return x;
            }
        }
    }

    /// `rngf` -- a float in `[0, n)`.
    ///
    /// Deliberately computed in `f32` throughout, including the lossy
    /// conversion of the 30-bit draw, so the result matches the C++ bit for
    /// bit. Promoting any of this to `f64` would silently change the values.
    pub fn rngf(&mut self, n: f32) -> f32 {
        let draw = (self.rng64() & 0x3fff_ffff) as f32;
        draw * (n / 0x3fff_ffff_u32 as f32)
    }

    /// `shuffle` -- Fisher-Yates, ascending, drawing `rng(size - i)` at each
    /// step.
    ///
    /// nextpnr iterates *upwards* and swaps `i` with `i + rng(size - i)`. The
    /// textbook descending variant consumes the stream in a different order
    /// and yields different permutations from the same seed.
    pub fn shuffle<T>(&mut self, slice: &mut [T]) {
        let size = slice.len();
        for i in 0..size {
            let j = i + self.rng_n((size - i) as i32) as usize;
            if j > i {
                slice.swap(i, j);
            }
        }
    }

    /// `sorted_shuffle` -- sort, then shuffle, so the result does not depend
    /// on the caller's input order.
    pub fn sorted_shuffle<T: Ord>(&mut self, slice: &mut [T]) {
        slice.sort();
        self.shuffle(slice);
    }

    // -----------------------------------------------------------------------
    // Aliases for eisenjoch's existing call sites. These are not part of
    // nextpnr's API; they exist so the port did not require rewriting every
    // caller.
    // -----------------------------------------------------------------------

    /// Alias for [`Self::rng64`].
    #[inline]
    pub fn next_u64(&mut self) -> u64 {
        self.rng64()
    }

    /// Low 32 bits of a draw.
    #[inline]
    pub fn next_u32(&mut self) -> u32 {
        self.rng64() as u32
    }

    /// Uniform in `[0, max)`, delegating to [`Self::rng_n`] so callers get the
    /// unbiased sampler rather than a modulo.
    ///
    /// # Panics
    ///
    /// Panics if `max` is 0.
    #[inline]
    pub fn next_range(&mut self, max: u32) -> u32 {
        assert!(max > 0, "next_range requires max > 0");
        self.rng_n(max as i32) as u32
    }
}
