#![allow(dead_code)]

use nextpnr::chipdb::testutil::make_test_chipdb;
use nextpnr::chipdb::ChipDb;
use nextpnr::common::IdString;
use nextpnr::context::Context;
use nextpnr::netlist::PortType;

pub fn make_context() -> Context {
    let chipdb = make_test_chipdb();
    Context::new(chipdb)
}

/// Path to the real example arch chipdb binary generated by build_chipdb.sh.
pub fn example_chipdb_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/example.bin")
}

/// Create a Context backed by the real example arch chipdb.
pub fn make_example_context() -> Context {
    let path = example_chipdb_path();
    let chipdb = ChipDb::load(&path).expect("failed to load example chipdb");
    Context::new(chipdb)
}

/// Add n cells of the given type and wire them together via a single net.
///
/// cell_0 drives `out_port`, cells 1..n consume via `in_port`.
/// If n < 2, no net is created.
fn add_cells_with_net(
    ctx: &mut Context,
    n: usize,
    cell_type: IdString,
    out_port: IdString,
    in_port: IdString,
) {
    let mut cell_names = Vec::with_capacity(n);

    for i in 0..n {
        let name = ctx.id(&format!("cell_{}", i));
        ctx.design.add_cell(name, cell_type);
        cell_names.push(name);
    }

    if n >= 2 {
        let net_name = ctx.id("net_0");
        let net_idx = ctx.design.add_net(net_name);

        let cell0_idx = ctx.design.cell_by_name(cell_names[0]).unwrap();
        ctx.design
            .cell_edit(cell0_idx)
            .add_port(out_port, PortType::Out);
        ctx.design
            .cell_edit(cell0_idx)
            .set_port_net(out_port, Some(net_idx), None);
        ctx.design
            .net_edit(net_idx)
            .set_driver(cell0_idx, out_port);

        for &name in &cell_names[1..] {
            let cell_idx = ctx.design.cell_by_name(name).unwrap();
            ctx.design
                .cell_edit(cell_idx)
                .add_port(in_port, PortType::In);

            let user_idx = ctx.design.net_edit(net_idx).add_user(cell_idx, in_port);
            ctx.design
                .cell_edit(cell_idx)
                .set_port_net(in_port, Some(net_idx), Some(user_idx));
        }
    }
}

/// Create a Context with n LUT4 cells wired together using the real example chipdb.
///
/// cell_0 drives "F" output, cells 1..n consume via "I[0]" input.
pub fn make_example_context_with_cells(n: usize) -> Context {
    let mut ctx = make_example_context();
    ctx.populate_bel_buckets();

    let cell_type = ctx.id("LUT4");
    let out_port = ctx.id("F");
    let in_port = ctx.id("I[0]");
    add_cells_with_net(&mut ctx, n, cell_type, out_port, in_port);

    ctx
}

pub fn make_context_with_cells(n: usize) -> Context {
    assert!(n <= 4, "synthetic chipdb only has 4 BELs");
    let mut ctx = make_context();
    ctx.populate_bel_buckets();

    let cell_type = ctx.id("LUT4");
    let out_port = ctx.id("Q");
    let in_port = ctx.id("A");
    add_cells_with_net(&mut ctx, n, cell_type, out_port, in_port);

    ctx
}
