//! Integration tests using a real himbaechel example arch chipdb (10x10 grid).
//!
//! The chipdb is generated by `tests/fixtures/build_chipdb.sh` from the example
//! arch Python generator and committed as `tests/fixtures/example.bin`.

mod common;

use nextpnr::chipdb::{BelId, ChipDb, TileTypePod};
use nextpnr::common::PlaceStrength;
use nextpnr::context::{BelPin, Context};
use nextpnr::placer::heap::{place_heap, PlacerHeapCfg};
use nextpnr::read_packed;
use nextpnr::router::router1::Router1Cfg;
use nextpnr::router::{Router, Router1};
use nextpnr::timing::ClockEdge;

// =====================================================================
// Test helpers
// =====================================================================

/// Find the first BEL of a given type in the chipdb.
fn find_bel(ctx: &Context, bel_type: &str) -> BelId {
    ctx.chipdb()
        .bels()
        .find(|&bel| ctx.chipdb().bel_type(bel) == bel_type)
        .unwrap_or_else(|| panic!("should find a {} BEL", bel_type))
}

/// Find the first tile of a given type in the chipdb.
fn find_tile(chipdb: &ChipDb, tile_type: &str) -> i32 {
    (0..chipdb.num_tiles())
        .find(|&t| chipdb.tile_type_name(t) == tile_type)
        .unwrap_or_else(|| panic!("should find a {} tile", tile_type))
}

/// Get the wire name string for a tile-type wire entry.
fn tile_wire_name<'a>(chipdb: &'a ChipDb, wire: &nextpnr::chipdb::TileWireDataPod) -> &'a str {
    let name_id: i32 = unsafe { read_packed!(*wire, name) };
    chipdb.constid_str(name_id).unwrap_or("<unknown>")
}

/// Find a wire index by name within a tile type.
fn find_wire_in_tile(chipdb: &ChipDb, tt: &TileTypePod, name: &str) -> usize {
    tt.wires
        .get()
        .iter()
        .enumerate()
        .find_map(|(i, w)| (tile_wire_name(chipdb, w) == name).then_some(i))
        .unwrap_or_else(|| panic!("tile should have wire {name}"))
}

/// Collect the names of source wires for all uphill PIPs of a given wire.
fn uphill_source_names(chipdb: &ChipDb, tt: &TileTypePod, wire_idx: usize) -> Vec<String> {
    let wire = &tt.wires.get()[wire_idx];
    wire.pips_uphill
        .get()
        .iter()
        .map(|&pip_idx| {
            let pip = &tt.pips.get()[pip_idx as usize];
            let src_idx: i32 = unsafe { read_packed!(*pip, src_wire) };
            tile_wire_name(chipdb, &tt.wires.get()[src_idx as usize]).to_string()
        })
        .collect()
}

/// Collect the names of destination wires for all downhill PIPs of a given wire.
fn downhill_dest_names(chipdb: &ChipDb, tt: &TileTypePod, wire_idx: usize) -> Vec<String> {
    let wire = &tt.wires.get()[wire_idx];
    wire.pips_downhill
        .get()
        .iter()
        .map(|&pip_idx| {
            let pip = &tt.pips.get()[pip_idx as usize];
            let dst_idx: i32 = unsafe { read_packed!(*pip, dst_wire) };
            tile_wire_name(chipdb, &tt.wires.get()[dst_idx as usize]).to_string()
        })
        .collect()
}

/// Find a constid index by its string name.
fn find_constid(chipdb: &ChipDb, name: &str) -> i32 {
    let total = chipdb.extra_constids().len() as i32;
    (0..total)
        .find(|&i| chipdb.constid_str(i).map_or(false, |s| s == name))
        .unwrap_or_else(|| panic!("{name} constid should exist"))
}

/// Collect all wire names in a tile type.
fn all_wire_names<'a>(chipdb: &'a ChipDb, tt: &TileTypePod) -> Vec<&'a str> {
    tt.wires.get().iter().map(|w| tile_wire_name(chipdb, w)).collect()
}

// =====================================================================
// Chipdb loading and basic metadata
// =====================================================================

#[test]
fn load_example_chipdb() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    assert_eq!(chipdb.name(), "EX1");
    assert_eq!(chipdb.uarch(), "example");
    assert_eq!(chipdb.width(), 10);
    assert_eq!(chipdb.height(), 10);
    assert_eq!(chipdb.num_tiles(), 100);
}

#[test]
fn chipdb_magic_and_version() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    assert_eq!(chipdb.chip_magic(), 0x00ca7ca7_u32 as i32);
    assert!(chipdb.chip_db_version() > 0);
}

// =====================================================================
// BEL enumeration
// =====================================================================

#[test]
fn enumerate_bels_exact_counts() {
    let ctx = common::make_example_context();
    let mut lut4_count = 0;
    let mut dff_count = 0;
    let mut iob_count = 0;
    let mut bram_count = 0;
    let mut gnd_count = 0;
    let mut vcc_count = 0;

    for bel in ctx.bels() {
        match bel.bel_type() {
            "LUT4" => lut4_count += 1,
            "DFF" => dff_count += 1,
            "IOB" => iob_count += 1,
            "BRAM_512X16" => bram_count += 1,
            "GND_DRV" => gnd_count += 1,
            "VCC_DRV" => vcc_count += 1,
            other => panic!("unexpected BEL type: {other}"),
        }
    }

    // 10x10 grid layout:
    //   4 NULL corners: 1 GND_DRV + 1 VCC_DRV each
    //   32 IO edge tiles (non-corner): 2 IOBs each
    //   8 BRAM tiles (x=1..8, y=7): 1 BRAM_512X16 each
    //   56 LOGIC tiles (8x8 interior minus 8 BRAM): 8 LUT4 + 8 DFF each
    assert_eq!(lut4_count, 448, "56 LOGIC tiles * 8 LUT4");
    assert_eq!(dff_count, 448, "56 LOGIC tiles * 8 DFF");
    assert_eq!(iob_count, 64, "32 IO tiles * 2 IOBs");
    assert_eq!(bram_count, 8, "8 BRAM tiles * 1 BRAM");
    assert_eq!(gnd_count, 4, "4 NULL corners * 1 GND_DRV");
    assert_eq!(vcc_count, 4, "4 NULL corners * 1 VCC_DRV");
}

#[test]
fn bel_names_are_meaningful() {
    let ctx = common::make_example_context();
    let bel = ctx.bels().next().unwrap();
    let name = bel.name();
    let btype = bel.bel_type();
    // Names should be non-empty strings from the chipdb, not "<unknown>"
    assert!(!name.is_empty());
    assert_ne!(name, "<unknown>");
    assert!(!btype.is_empty());
    assert_ne!(btype, "<unknown>");
}

// =====================================================================
// Direct BEL binding
// =====================================================================

#[test]
fn bind_lut4_to_bel() {
    let mut ctx = common::make_example_context();
    ctx.populate_bel_buckets();

    let cell_type = ctx.id("LUT4");
    let cell_name = ctx.id("test_lut");
    ctx.design.add_cell(cell_name, cell_type);
    let cell_idx = ctx.design.cell_by_name(cell_name).unwrap();

    let lut_bel = find_bel(&ctx, "LUT4");
    assert!(ctx.bind_bel(lut_bel, cell_idx, PlaceStrength::Placer));

    // Verify the cell is now bound
    let cell_view = ctx.cell(cell_idx);
    assert_eq!(cell_view.bel_id(), Some(lut_bel));

    // Verify the BEL reports the cell
    let bel_view = ctx.bel(lut_bel);
    assert!(!bel_view.is_available());
}

#[test]
fn bind_and_unbind_bel() {
    let mut ctx = common::make_example_context();

    let cell_type = ctx.id("LUT4");
    let cell_name = ctx.id("test_lut");
    ctx.design.add_cell(cell_name, cell_type);
    let cell_idx = ctx.design.cell_by_name(cell_name).unwrap();

    let lut_bel = find_bel(&ctx, "LUT4");
    assert!(ctx.bind_bel(lut_bel, cell_idx, PlaceStrength::Placer));
    ctx.unbind_bel(lut_bel);

    assert!(ctx.bel(lut_bel).is_available());
    assert!(ctx.cell(cell_idx).bel_id().is_none());
}

#[test]
fn double_bind_fails() {
    let mut ctx = common::make_example_context();

    let cell_type = ctx.id("LUT4");
    let name_a = ctx.id("cell_a");
    let name_b = ctx.id("cell_b");
    ctx.design.add_cell(name_a, cell_type);
    ctx.design.add_cell(name_b, cell_type);
    let cell_a = ctx.design.cell_by_name(name_a).unwrap();
    let cell_b = ctx.design.cell_by_name(name_b).unwrap();

    let lut_bel = find_bel(&ctx, "LUT4");
    assert!(ctx.bind_bel(lut_bel, cell_a, PlaceStrength::Placer));
    assert!(!ctx.bind_bel(lut_bel, cell_b, PlaceStrength::Placer));
}

// =====================================================================
// BEL pin wires
// =====================================================================

#[test]
fn bel_pin_wire_resolves_lut4_pins() {
    let ctx = common::make_example_context();

    let lut_bel = find_bel(&ctx, "LUT4");

    // LUT4 has pins I[0]..I[3] and F
    let f_port = ctx.id("F");
    let bp = BelPin::new(lut_bel, f_port);
    let wire = ctx.bel_pin_wire(bp);
    assert!(wire.is_some(), "F pin should resolve to a wire");
}

#[test]
fn bel_pin_wire_resolves_dff_pins() {
    let ctx = common::make_example_context();

    let dff_bel = find_bel(&ctx, "DFF");

    // DFF has pins D, CLK, Q
    for pin_name in &["D", "CLK", "Q"] {
        let port = ctx.id(*pin_name);
        let bp = BelPin::new(dff_bel, port);
        let wire = ctx.bel_pin_wire(bp);
        assert!(wire.is_some(), "DFF pin {pin_name} should resolve to a wire");
    }
}

// =====================================================================
// Wire and PIP traversal
// =====================================================================

#[test]
fn pip_src_dst_wires_are_valid() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    let pips: Vec<_> = chipdb.pips().take(100).collect();
    assert_eq!(pips.len(), 100, "chipdb should have at least 100 PIPs");

    for pip in pips {
        let src = chipdb.pip_src_wire(pip);
        let dst = chipdb.pip_dst_wire(pip);
        assert_eq!(src.tile(), pip.tile());
        assert_eq!(dst.tile(), pip.tile());
        let tt = chipdb.tile_type(pip.tile());
        assert!((src.index() as usize) < tt.wires.get().len());
        assert!((dst.index() as usize) < tt.wires.get().len());
    }
}

#[test]
fn wire_names_are_valid() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);
    for wire_idx in 0..tt.wires.get().len().min(5) {
        let wire_id = nextpnr::chipdb::WireId::new(logic_tile, wire_idx as i32);
        let name = chipdb.wire_name(wire_id);
        assert!(!name.is_empty());
        assert_ne!(name, "<unknown>");
    }
}

// =====================================================================
// Tile name resolution
// =====================================================================

#[test]
fn tile_names_and_types() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    // Corner tiles should be NULL type
    let corner = chipdb.tile_by_xy(0, 0);
    assert_eq!(chipdb.tile_type_name(corner), "NULL");

    // Edge tiles (non-corner) should be IO
    let edge = chipdb.tile_by_xy(0, 1);
    assert_eq!(chipdb.tile_type_name(edge), "IO");

    // Interior tiles should be LOGIC (except BRAM rows)
    let interior = chipdb.tile_by_xy(1, 1);
    assert_eq!(chipdb.tile_type_name(interior), "LOGIC");

    // Check BRAM row (y%15==7)
    let bram = chipdb.tile_by_xy(1, 7);
    assert_eq!(chipdb.tile_type_name(bram), "BRAM");

    // tile_name should produce a readable string
    let name = chipdb.tile_name(interior);
    assert!(name.contains("X1Y1"), "tile name should contain coordinates, got: {name}");
}

#[test]
fn tile_xy_roundtrip() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    for y in 0..chipdb.height() {
        for x in 0..chipdb.width() {
            let tile = chipdb.tile_by_xy(x, y);
            let (rx, ry) = chipdb.tile_xy(tile);
            assert_eq!((rx, ry), (x, y));
        }
    }
}

// =====================================================================
// BEL bucket enumeration
// =====================================================================

#[test]
fn bel_buckets_contain_expected_types() {
    let mut ctx = common::make_example_context();
    ctx.populate_bel_buckets();

    let buckets = ctx.bel_buckets();
    let bucket_names: Vec<&str> = buckets.iter().map(|b| ctx.name_of(*b)).collect();

    assert!(bucket_names.contains(&"LUT4"), "should have LUT4 bucket");
    assert!(bucket_names.contains(&"DFF"), "should have DFF bucket");
    assert!(bucket_names.contains(&"IOB"), "should have IOB bucket");
    assert!(bucket_names.contains(&"BRAM_512X16"), "should have BRAM bucket");
}

#[test]
fn bels_for_bucket_returns_correct_types() {
    let mut ctx = common::make_example_context();
    ctx.populate_bel_buckets();

    let lut4_bucket = ctx.id("LUT4");
    for bel in ctx.bels_for_bucket(lut4_bucket) {
        assert_eq!(bel.bel_type(), "LUT4");
    }
}

// =====================================================================
// BEL location consistency
// =====================================================================

#[test]
fn bel_loc_matches_tile_xy() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    for bel_id in chipdb.bels().take(50) {
        let loc = chipdb.bel_loc(bel_id);
        let (tx, ty) = chipdb.tile_xy(bel_id.tile());
        assert_eq!(loc.x, tx);
        assert_eq!(loc.y, ty);
    }
}

// =====================================================================
// HeAP placement with real chipdb
// =====================================================================

#[test]
fn heap_placement_small() {
    let mut ctx = common::make_example_context_with_cells(4);
    let cfg = PlacerHeapCfg {
        seed: 42,
        max_iterations: 5,
        ..PlacerHeapCfg::default()
    };
    place_heap(&mut ctx, &cfg).expect("HeAP should succeed on example chipdb");

    for cell in ctx.cells() {
        if !cell.is_alive() {
            continue;
        }
        assert!(
            cell.bel_id().is_some(),
            "cell {} should be placed",
            cell.name()
        );
    }
}

#[test]
fn heap_placement_medium() {
    let mut ctx = common::make_example_context_with_cells(16);
    let cfg = PlacerHeapCfg {
        seed: 99,
        max_iterations: 10,
        ..PlacerHeapCfg::default()
    };
    place_heap(&mut ctx, &cfg).expect("HeAP should handle 16 cells");

    let mut placed = std::collections::HashSet::new();
    for cell in ctx.cells() {
        if !cell.is_alive() {
            continue;
        }
        let bel = cell.bel_id().expect("cell should be placed");
        assert!(placed.insert(bel), "each cell should be on a unique BEL");
    }
    assert_eq!(placed.len(), 16);
}

// =====================================================================
// Timing data present
// =====================================================================

#[test]
fn speed_grades_present() {
    let ctx = common::make_example_context();
    assert!(ctx.chipdb().num_speed_grades() > 0, "should have speed grade data");
}

#[test]
fn pip_timing_data_exists() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let sg = chipdb.speed_grade(0).expect("should have speed grade 0");

    // At least some PIPs should have timing data
    let mut with_timing = 0;
    for pip in chipdb.pips().take(200) {
        if chipdb.pip_timing(&sg, pip).is_some() {
            with_timing += 1;
        }
    }
    assert!(with_timing > 0, "some PIPs should have timing data");
}

// =====================================================================
// Exact tile type counts
// =====================================================================

#[test]
fn exact_tile_type_counts() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let mut null_count = 0;
    let mut io_count = 0;
    let mut logic_count = 0;
    let mut bram_count = 0;

    for tile in 0..chipdb.num_tiles() {
        match chipdb.tile_type_name(tile) {
            "NULL" => null_count += 1,
            "IO" => io_count += 1,
            "LOGIC" => logic_count += 1,
            "BRAM" => bram_count += 1,
            other => panic!("unexpected tile type: {other}"),
        }
    }

    assert_eq!(null_count, 4, "4 corner NULL tiles");
    assert_eq!(io_count, 32, "32 edge IO tiles");
    assert_eq!(logic_count, 56, "56 interior LOGIC tiles");
    assert_eq!(bram_count, 8, "8 BRAM tiles at y=7");
}

// =====================================================================
// BEL pin direction checks
// =====================================================================

#[test]
fn lut4_pin_directions() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let lut_bel = find_bel(&ctx, "LUT4");
    let bel_info = chipdb.bel_info(lut_bel);

    let mut input_count = 0;
    let mut output_count = 0;

    for pin in bel_info.pins.get() {
        let (name_id, _wire, dir) = chipdb.bel_pin_fields(pin);
        let name = chipdb.constid_str(name_id).unwrap();
        match dir {
            0 => {
                // INPUT
                assert!(
                    name.starts_with("I["),
                    "LUT4 input pin should be I[n], got {name}"
                );
                input_count += 1;
            }
            1 => {
                // OUTPUT
                assert_eq!(name, "F", "LUT4 output pin should be F");
                output_count += 1;
            }
            _ => panic!("unexpected pin direction {dir} for LUT4 pin {name}"),
        }
    }

    assert_eq!(input_count, 4, "LUT4 should have 4 inputs (K=4)");
    assert_eq!(output_count, 1, "LUT4 should have 1 output (F)");
}

#[test]
fn dff_pin_directions() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let dff_bel = find_bel(&ctx, "DFF");
    let bel_info = chipdb.bel_info(dff_bel);

    let mut pins: Vec<(String, i32)> = Vec::new();
    for pin in bel_info.pins.get() {
        let (name_id, _wire, dir) = chipdb.bel_pin_fields(pin);
        let name = chipdb.constid_str(name_id).unwrap().to_string();
        pins.push((name, dir));
    }

    // Sort for deterministic checking
    pins.sort_by(|a, b| a.0.cmp(&b.0));
    assert_eq!(pins.len(), 3, "DFF should have 3 pins");
    assert_eq!(pins[0], ("CLK".to_string(), 0), "CLK is input");
    assert_eq!(pins[1], ("D".to_string(), 0), "D is input");
    assert_eq!(pins[2], ("Q".to_string(), 1), "Q is output");
}

#[test]
fn iob_pin_directions() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let iob_bel = find_bel(&ctx, "IOB");
    let bel_info = chipdb.bel_info(iob_bel);

    let mut pins: Vec<(String, i32)> = Vec::new();
    for pin in bel_info.pins.get() {
        let (name_id, _wire, dir) = chipdb.bel_pin_fields(pin);
        let name = chipdb.constid_str(name_id).unwrap().to_string();
        pins.push((name, dir));
    }
    pins.sort_by(|a, b| a.0.cmp(&b.0));

    assert_eq!(pins.len(), 4, "IOB should have 4 pins");
    assert_eq!(pins[0], ("I".to_string(), 0), "I is input");
    assert_eq!(pins[1], ("O".to_string(), 1), "O is output");
    assert_eq!(pins[2], ("PAD".to_string(), 2), "PAD is inout");
    assert_eq!(pins[3], ("T".to_string(), 0), "T is input");
}

// =====================================================================
// PIP connectivity semantics
// =====================================================================

#[test]
fn logic_tile_has_lut_input_pips() {
    // In a LOGIC tile, there should be PIPs from SWITCH wires to LUT input wires
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    let l0_i0_idx = find_wire_in_tile(chipdb, tt, "L0_I0");
    let sources = uphill_source_names(chipdb, tt, l0_i0_idx);

    assert!(!sources.is_empty(), "L0_I0 should have uphill PIPs from switch wires");
    assert!(
        sources.iter().any(|n| n.starts_with("SWITCH")),
        "L0_I0 should be driven by a SWITCH wire"
    );
}

#[test]
fn logic_tile_has_lut_output_pips() {
    // LUT output wires should have downhill PIPs to SWITCH wires
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    let l0_o_idx = find_wire_in_tile(chipdb, tt, "L0_O");
    let dests = downhill_dest_names(chipdb, tt, l0_o_idx);

    assert!(!dests.is_empty(), "L0_O should have downhill PIPs");
    assert!(
        dests.iter().any(|n| n.starts_with("SWITCH")),
        "L0_O should drive SWITCH wires"
    );
}

#[test]
fn logic_tile_has_ff_data_pip_from_lut() {
    // FF data wire L0_D should have a PIP from L0_O (LUT output to FF input)
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    let l0_d_idx = find_wire_in_tile(chipdb, tt, "L0_D");
    let sources = uphill_source_names(chipdb, tt, l0_d_idx);

    assert!(
        sources.contains(&"L0_O".to_string()),
        "L0_D should have PIP from L0_O, got sources: {sources:?}"
    );
    assert!(
        sources.contains(&"L0_I3".to_string()),
        "L0_D should have PIP from L0_I3, got sources: {sources:?}"
    );
}

#[test]
fn logic_tile_has_neighbor_pips() {
    // SWITCH wires should have uphill PIPs from neighbor wires (N, S, E, W, etc.)
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    let switch0_idx = find_wire_in_tile(chipdb, tt, "SWITCH0");
    let sources = uphill_source_names(chipdb, tt, switch0_idx);

    for dir in &["N", "NE", "E", "SE", "S", "SW", "W", "NW"] {
        assert!(
            sources.iter().any(|n| n.starts_with(dir)),
            "SWITCH0 should have uphill PIP from {dir}* neighbor wire, got: {sources:?}"
        );
    }
}

#[test]
fn logic_tile_has_constant_pips() {
    // SWITCH wires should have uphill PIPs from GND and VCC
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    let switch0_idx = find_wire_in_tile(chipdb, tt, "SWITCH0");
    let sources = uphill_source_names(chipdb, tt, switch0_idx);

    assert!(sources.contains(&"GND".to_string()), "SWITCH0 should have GND PIP");
    assert!(sources.contains(&"VCC".to_string()), "SWITCH0 should have VCC PIP");
}

// =====================================================================
// Wire connectivity across tiles (routing graph)
// =====================================================================

#[test]
fn wire_pips_uphill_downhill_consistency() {
    // For every PIP in a tile, the dst wire's pips_uphill should contain it,
    // and the src wire's pips_downhill should contain it.
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    for (pip_idx, pip) in tt.pips.get().iter().enumerate() {
        let src_wire_idx: i32 = unsafe { read_packed!(*pip, src_wire) };
        let dst_wire_idx: i32 = unsafe { read_packed!(*pip, dst_wire) };

        // dst wire's pips_uphill should contain this pip index
        let dst_wire = &tt.wires.get()[dst_wire_idx as usize];
        let uphill_contains = dst_wire
            .pips_uphill
            .get()
            .iter()
            .any(|&idx| idx as usize == pip_idx);
        assert!(
            uphill_contains,
            "PIP {} ({}→{}) not found in dst wire pips_uphill",
            pip_idx, src_wire_idx, dst_wire_idx
        );

        // src wire's pips_downhill should contain this pip index
        let src_wire = &tt.wires.get()[src_wire_idx as usize];
        let downhill_contains = src_wire
            .pips_downhill
            .get()
            .iter()
            .any(|&idx| idx as usize == pip_idx);
        assert!(
            downhill_contains,
            "PIP {} ({}→{}) not found in src wire pips_downhill",
            pip_idx, src_wire_idx, dst_wire_idx
        );
    }
}

#[test]
fn bel_pin_wires_have_bel_pin_refs() {
    // For each BEL pin, the connected wire should have a bel_pin_ref back to that BEL
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    for (bel_idx, bel_data) in tt.bels.get().iter().enumerate() {
        for pin in bel_data.pins.get() {
            let (pin_name_id, wire_idx, _dir) = chipdb.bel_pin_fields(pin);
            let wire = &tt.wires.get()[wire_idx as usize];
            let has_back_ref = wire.bel_pins.get().iter().any(|bp_ref| {
                let ref_bel: i32 = unsafe { read_packed!(*bp_ref, bel) };
                let ref_pin: i32 = unsafe { read_packed!(*bp_ref, pin) };
                ref_bel as usize == bel_idx && ref_pin == pin_name_id
            });
            let pin_name = chipdb.constid_str(pin_name_id).unwrap_or("?");
            let bel_name_id: i32 = unsafe { read_packed!(*bel_data, name) };
            let bel_name = chipdb.constid_str(bel_name_id).unwrap_or("?");
            assert!(
                has_back_ref,
                "wire {} should have bel_pin_ref back to BEL {} pin {}",
                wire_idx, bel_name, pin_name
            );
        }
    }
}

// =====================================================================
// Timing value verification
// =====================================================================

#[test]
fn lut4_combinational_delays() {
    // LUT4 should have comb arcs I[0]->F: 150ps, I[1]->F: 165ps, I[2]->F: 180ps, I[3]->F: 195ps
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let sg = chipdb.speed_grade(0).unwrap();

    let lut4_id = find_constid(chipdb, "LUT4");
    let f_id = find_constid(chipdb, "F");
    let type_idx = chipdb.cell_timing_index(&sg, lut4_id).expect("LUT4 should have timing data");

    let expected_delays = [(150, "I[0]"), (165, "I[1]"), (180, "I[2]"), (195, "I[3]")];
    for (expected_ps, pin_name) in &expected_delays {
        let pin_id = find_constid(chipdb, pin_name);
        let delay = chipdb
            .cell_delay(&sg, type_idx, pin_id, f_id)
            .unwrap_or_else(|| panic!("LUT4 should have {pin_name}->F delay"));

        assert_eq!(
            delay.max_delay(),
            *expected_ps,
            "LUT4 {pin_name}->F delay should be {expected_ps}ps"
        );
    }
}

#[test]
fn dff_register_timing() {
    // DFF should have: setup(CLK,D)=150ps, hold=25ps, clk_to_q(CLK,Q)=200ps
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let sg = chipdb.speed_grade(0).unwrap();

    let dff_id = find_constid(chipdb, "DFF");
    let d_id = find_constid(chipdb, "D");
    let q_id = find_constid(chipdb, "Q");

    let type_idx = chipdb.cell_timing_index(&sg, dff_id).expect("DFF should have timing data");

    // Check D pin has register arcs (setup/hold)
    let d_arcs = chipdb
        .cell_reg_arcs(&sg, type_idx, d_id)
        .expect("DFF D pin should have register arcs");
    assert!(!d_arcs.is_empty(), "DFF D should have setup/hold arcs");

    let d_arc_info = nextpnr::chipdb::ChipDb::reg_arc_info(&d_arcs[0]);
    assert_eq!(d_arc_info.edge, ClockEdge::Rising, "DFF should be rising edge");
    // Setup time: TimingValue(150) → all corners = 150
    assert_eq!(d_arc_info.setup.max_delay, 150, "DFF setup should be 150ps");
    // Hold time: TimingValue(25) → all corners = 25
    assert_eq!(d_arc_info.hold.max_delay, 25, "DFF hold should be 25ps");

    // Check Q pin has register arcs (clock-to-Q)
    let q_arcs = chipdb
        .cell_reg_arcs(&sg, type_idx, q_id)
        .expect("DFF Q pin should have register arcs");
    assert!(!q_arcs.is_empty(), "DFF Q should have clk-to-Q arcs");

    let q_arc_info = nextpnr::chipdb::ChipDb::reg_arc_info(&q_arcs[0]);
    assert_eq!(q_arc_info.edge, ClockEdge::Rising);
    assert_eq!(
        q_arc_info.clock_to_q.max_delay(),
        200,
        "DFF clk-to-Q should be 200ps"
    );
}

#[test]
fn pip_timing_values_match_generator() {
    // SWINPUT class: delay=80ps, SWNEIGH class: delay=120ps
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let sg = chipdb.speed_grade(0).unwrap();

    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    // Collect all unique PIP timing indices and their delays
    let mut seen_delays = std::collections::HashSet::new();
    for (pip_idx, _pip) in tt.pips.get().iter().enumerate() {
        let pip_id = nextpnr::chipdb::PipId::new(logic_tile, pip_idx as i32);
        if let Some(pip_tmg) = chipdb.pip_timing(&sg, pip_id) {
            let int_delay = unsafe { read_packed!(*pip_tmg, int_delay) };
            seen_delays.insert(int_delay.slow_max);
        }
    }

    // We should see the SWINPUT (80ps) and SWNEIGH (120ps) delay values
    assert!(
        seen_delays.contains(&80),
        "should find SWINPUT delay of 80ps, got: {seen_delays:?}"
    );
    assert!(
        seen_delays.contains(&120),
        "should find SWNEIGH delay of 120ps, got: {seen_delays:?}"
    );
}

// =====================================================================
// Wire-level checks on specific tile types
// =====================================================================

#[test]
fn logic_tile_wire_count() {
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let logic_tile = find_tile(chipdb, "LOGIC");
    let tt = chipdb.tile_type(logic_tile);

    let wire_count = tt.wires.get().len();
    assert!(
        wire_count > 100,
        "LOGIC tile should have many wires (switch matrix), got {wire_count}"
    );

    let wire_names = all_wire_names(chipdb, tt);
    for expected in &["L0_I0", "L7_Q", "CLK", "SWITCH0", "GND", "VCC", "N0"] {
        assert!(
            wire_names.contains(expected),
            "should have {expected} wire"
        );
    }
}

#[test]
fn bram_tile_has_expected_bel_pins() {
    // BRAM_512X16 should have: CLK + 9 WA + 9 RA + 2 WE + 16 DI + 16 DO = 53 pins
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let bram_bel = find_bel(&ctx, "BRAM_512X16");
    let bel_info = chipdb.bel_info(bram_bel);

    let pin_count = bel_info.pins.get().len();
    assert_eq!(pin_count, 53, "BRAM should have 53 pins (CLK + 9WA + 9RA + 2WE + 16DI + 16DO)");

    let mut input_count = 0;
    let mut output_count = 0;
    for pin in bel_info.pins.get() {
        let (_name_id, _wire, dir) = chipdb.bel_pin_fields(pin);
        match dir {
            0 => input_count += 1,
            1 => output_count += 1,
            _ => {}
        }
    }
    // CLK + 9 WA + 9 RA + 2 WE + 16 DI = 37 inputs
    assert_eq!(input_count, 37, "BRAM should have 37 input pins");
    // 16 DO = 16 outputs
    assert_eq!(output_count, 16, "BRAM should have 16 output pins");
}

#[test]
fn all_bel_pin_wires_resolve() {
    // Every BEL pin across the entire chipdb should resolve to a valid wire
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();
    let mut total_pins = 0;

    for bel_id in chipdb.bels() {
        let bel_info = chipdb.bel_info(bel_id);
        for pin in bel_info.pins.get() {
            let (name_id, wire_idx, _dir) = chipdb.bel_pin_fields(pin);
            let tt = chipdb.tile_type(bel_id.tile());
            assert!(
                (wire_idx as usize) < tt.wires.get().len(),
                "BEL pin wire index {} out of range for tile {}",
                wire_idx,
                bel_id.tile()
            );

            // Also verify via the Context API
            let pin_name = chipdb.constid_str(name_id).unwrap_or("?");
            let port = ctx.id(pin_name);
            let bp = BelPin::new(bel_id, port);
            assert!(
                ctx.bel_pin_wire(bp).is_some(),
                "bel_pin_wire should resolve for BEL {} pin {}",
                chipdb.bel_name(bel_id),
                pin_name
            );
            total_pins += 1;
        }
    }
    // Sanity check: we should have checked a large number of pins
    assert!(total_pins > 1000, "should check many pins, got {total_pins}");
}

// =====================================================================
// Utilization report
// =====================================================================

#[test]
fn utilization_report_empty_design() {
    let ctx = common::make_example_context();
    let report = ctx.utilization_report();

    assert_eq!(report.total_cells, 0);
    assert_eq!(report.total_nets, 0);
    assert_eq!(report.placed_cells, 0);

    // Should still list all available BEL types
    let bram_row = report.rows.iter().find(|r| r.resource == "BRAM_512X16");
    assert!(bram_row.is_some(), "should list BRAM resource type");
    assert_eq!(bram_row.unwrap().available, 8);
    assert_eq!(bram_row.unwrap().used, 0);
}

#[test]
fn utilization_report_with_cells() {
    let ctx = common::make_example_context_with_cells(10);
    let report = ctx.utilization_report();

    assert_eq!(report.total_cells, 10);
    assert_eq!(report.placed_cells, 0, "cells not yet placed");

    let lut_row = report.rows.iter().find(|r| r.resource == "LUT4").unwrap();
    assert_eq!(lut_row.used, 10);
    assert_eq!(lut_row.available, 448, "10x10 grid has 56 LOGIC tiles * 8 LUTs");
}

#[test]
fn utilization_report_after_placement() {
    let mut ctx = common::make_example_context_with_cells(4);
    let cfg = PlacerHeapCfg {
        seed: 42,
        ..PlacerHeapCfg::default()
    };
    place_heap(&mut ctx, &cfg).expect("placement should succeed");

    let report = ctx.utilization_report();
    assert_eq!(report.total_cells, 4);
    assert_eq!(report.placed_cells, 4, "all cells should be placed");

    let lut_row = report.rows.iter().find(|r| r.resource == "LUT4").unwrap();
    assert!(lut_row.percent() < 1.0, "4/448 is under 1%");
}

#[test]
fn utilization_report_format() {
    let ctx = common::make_example_context_with_cells(10);
    let report = ctx.utilization_report();
    let text = report.to_string();

    assert!(text.contains("Resource Utilization"));
    assert!(text.contains("LUT4"));
    assert!(text.contains("10")); // used count
    assert!(text.contains("448")); // available count
}

#[test]
fn clock_wire_exists_in_all_non_null_tiles() {
    // All tile types in this arch have a CLK wire (even NULL)
    let ctx = common::make_example_context();
    let chipdb = ctx.chipdb();

    for tile in 0..chipdb.num_tiles() {
        let tt = chipdb.tile_type(tile);
        let has_clk = tt.wires.get().iter().any(|w| tile_wire_name(chipdb, w) == "CLK");
        assert!(
            has_clk,
            "tile {} ({}) should have CLK wire",
            tile,
            chipdb.tile_type_name(tile)
        );
    }
}

// =====================================================================
// Routing on real chipdb
// =====================================================================

/// Find LUT4 BELs in a single LOGIC tile where routing from driver to consumers
/// is possible within the tile's switch matrix.
///
/// The example arch switch matrix has a staggered pattern:
///   L(n)_O -> SWITCH(n*6 mod 60) -> L(m)_I(k)
/// So L2_O -> SWITCH4 -> L1_I0 works (driver=L2, consumer=L1 via I[0]).
///
/// Returns (driver_bel, consumer_bels) where driver_bel's F output can reach
/// each consumer_bel's I[0] input through the intra-tile switch matrix.
fn find_routable_lut4_bels(ctx: &Context) -> (BelId, Vec<BelId>) {
    let chipdb = ctx.chipdb();
    let logic_tile = (0..chipdb.num_tiles())
        .find(|&t| chipdb.tile_type_name(t) == "LOGIC")
        .expect("should have a LOGIC tile");

    let mut lut4_bels: Vec<BelId> = chipdb
        .bels()
        .filter(|&bel| bel.tile() == logic_tile && chipdb.bel_type(bel) == "LUT4")
        .collect();
    lut4_bels.sort_by_key(|b| b.index());

    // Find a driver whose F output can reach other LUT I[0] inputs via the switch matrix.
    let f_port = ctx.id("F");
    let i0_port = ctx.id("I[0]");
    for &driver_bel in &lut4_bels {
        let src_wire = match ctx.bel_pin_wire(BelPin::new(driver_bel, f_port)) {
            Some(w) => w.id(),
            None => continue,
        };
        // Find which consumer BELs' I[0] pins are reachable from this driver
        let mut reachable = Vec::new();
        for &consumer_bel in &lut4_bels {
            if consumer_bel == driver_bel {
                continue;
            }
            let sink_wire = match ctx.bel_pin_wire(BelPin::new(consumer_bel, i0_port)) {
                Some(w) => w.id(),
                None => continue,
            };
            // Check 2-hop: src_wire -> SWITCH -> sink_wire
            let src_info = chipdb.wire_info(src_wire);
            let reachable_via_switch = src_info.pips_downhill.get().iter().any(|&pip_idx| {
                let pip = nextpnr::chipdb::PipId::new(logic_tile, pip_idx);
                let sw_wire = chipdb.pip_dst_wire(pip);
                let sw_info = chipdb.wire_info(sw_wire);
                sw_info.pips_downhill.get().iter().any(|&pip_idx2| {
                    let pip2 = nextpnr::chipdb::PipId::new(logic_tile, pip_idx2);
                    chipdb.pip_dst_wire(pip2) == sink_wire
                })
            });
            if reachable_via_switch {
                reachable.push(consumer_bel);
            }
        }
        if !reachable.is_empty() {
            return (driver_bel, reachable);
        }
    }
    panic!("could not find any routable LUT4 driver->consumer pair in a single tile");
}

#[test]
fn route_single_net_on_real_chipdb() {
    let mut ctx = common::make_example_context_with_cells(2);

    // Place cells on BELs where the driver's F output can reach the
    // consumer's I[0] input through the intra-tile switch matrix.
    let (driver_bel, consumers) = find_routable_lut4_bels(&ctx);
    let cell0 = ctx.design.cell_by_name(ctx.id("cell_0")).unwrap();
    let cell1 = ctx.design.cell_by_name(ctx.id("cell_1")).unwrap();
    assert!(ctx.bind_bel(driver_bel, cell0, PlaceStrength::Placer));
    assert!(ctx.bind_bel(consumers[0], cell1, PlaceStrength::Placer));

    let router_cfg = Router1Cfg::default();
    let net_name = ctx.id("net_0");
    let net_idx = ctx.design.net_by_name(net_name).unwrap();

    Router1
        .route_net(&mut ctx, &router_cfg, net_idx)
        .expect("routing single net should succeed");

    // Verify the net has routed wires
    let net = ctx.net(net_idx);
    assert!(
        net.wires().len() >= 2,
        "routed net should have at least source + sink wires, got {}",
        net.wires().len()
    );
}

#[test]
fn route_nets_subset() {
    let mut ctx = common::make_example_context_with_cells(4);

    // Place driver and consumers on BELs with intra-tile switch connectivity.
    let (driver_bel, consumers) = find_routable_lut4_bels(&ctx);
    let cell0 = ctx.design.cell_by_name(ctx.id("cell_0")).unwrap();
    assert!(ctx.bind_bel(driver_bel, cell0, PlaceStrength::Placer));
    for (i, &consumer_bel) in consumers.iter().take(3).enumerate() {
        let cell_name = ctx.id(&format!("cell_{}", i + 1));
        let cell_idx = ctx.design.cell_by_name(cell_name).unwrap();
        assert!(ctx.bind_bel(consumer_bel, cell_idx, PlaceStrength::Placer));
    }

    let router_cfg = Router1Cfg::default();
    let net_name = ctx.id("net_0");
    let net_idx = ctx.design.net_by_name(net_name).unwrap();

    // Route just net_0 via route_nets
    Router1
        .route_nets(&mut ctx, &router_cfg, &[net_idx])
        .expect("routing net subset should succeed");

    let net = ctx.net(net_idx);
    assert!(
        net.wires().len() >= 2,
        "routed net should have wires, got {}",
        net.wires().len()
    );
}

#[test]
fn route_all_via_trait() {
    let mut ctx = common::make_example_context_with_cells(4);

    // Place driver and consumers on BELs with intra-tile switch connectivity.
    let (driver_bel, consumers) = find_routable_lut4_bels(&ctx);
    let cell0 = ctx.design.cell_by_name(ctx.id("cell_0")).unwrap();
    assert!(ctx.bind_bel(driver_bel, cell0, PlaceStrength::Placer));
    for (i, &consumer_bel) in consumers.iter().take(3).enumerate() {
        let cell_name = ctx.id(&format!("cell_{}", i + 1));
        let cell_idx = ctx.design.cell_by_name(cell_name).unwrap();
        assert!(ctx.bind_bel(consumer_bel, cell_idx, PlaceStrength::Placer));
    }

    let router_cfg = Router1Cfg::default();
    Router1
        .route(&mut ctx, &router_cfg)
        .expect("full routing should succeed");

    // Verify all routable nets have wires
    let net_name = ctx.id("net_0");
    let net_idx = ctx.design.net_by_name(net_name).unwrap();
    let net = ctx.net(net_idx);
    assert!(
        net.wires().len() >= 2,
        "net_0 should be routed after route(), got {} wires",
        net.wires().len()
    );
}
